// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJHi56Rt145tL8q9J0kNV6x4I-cNubgA',
    appId: '1:830069791687:web:5541d97262e6637eee57e2',
    messagingSenderId: '830069791687',
    projectId: 'heart-bridge-2025',
    authDomain: 'heart-bridge-2025.firebaseapp.com',
    storageBucket: 'heart-bridge-2025.firebasestorage.app',
    measurementId: 'G-7EHXRMWLCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD78nsG9qZ_XXLuoZfnl3-6apbIOH3D5lQ',
    appId: '1:830069791687:android:057ead0b5ccce801ee57e2',
    messagingSenderId: '830069791687',
    projectId: 'heart-bridge-2025',
    storageBucket: 'heart-bridge-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2t7WNUWcnFxM1kICl0iKFsx5YJt-bCw',
    appId: '1:830069791687:ios:933f5d265cfe8a09ee57e2',
    messagingSenderId: '830069791687',
    projectId: 'heart-bridge-2025',
    storageBucket: 'heart-bridge-2025.firebasestorage.app',
    iosBundleId: 'com.heartbridge.heartBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2t7WNUWcnFxM1kICl0iKFsx5YJt-bCw',
    appId: '1:830069791687:ios:933f5d265cfe8a09ee57e2',
    messagingSenderId: '830069791687',
    projectId: 'heart-bridge-2025',
    storageBucket: 'heart-bridge-2025.firebasestorage.app',
    iosBundleId: 'com.heartbridge.heartBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJHi56Rt145tL8q9J0kNV6x4I-cNubgA',
    appId: '1:830069791687:web:66376304a8e30414ee57e2',
    messagingSenderId: '830069791687',
    projectId: 'heart-bridge-2025',
    authDomain: 'heart-bridge-2025.firebaseapp.com',
    storageBucket: 'heart-bridge-2025.firebasestorage.app',
    measurementId: 'G-P5JXRB5YSP',
  );
}
